# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        MainBundle\Entity\User: 
            algorithm: bcrypt
        #Symfony\Component\Security\Core\User\User: plaintext
        
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]

    providers:
        stt_db_provider:
            entity:
                class: MainBundle:User
                property: username
        # in_memory:
        #     memory:
        #         users:
        #             testuser:
        #                 password: test
        #                 roles: 'ROLE_ADMIN'
        #             testuser2:
        #                 password: test
        #                 roles: 'ROLE_USER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false 
        main:
            anonymous: ~
            # activate different ways to authenticate
            #http_basic: true
            
            form_login:
                login_path: login
                check_path: login
            
            logout:
                path:   /logout
                target: /

            provider: stt_db_provider
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

            
            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
     
